# Generated by Django 6.0.4 on 2026-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
