# Generated by Django 6.0.4 on 2026-05-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_orden_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
